# Generated by Django 6.0.1 on 2026-01-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('TT', 'Télétravail'), ('R', 'Réunion'), ('CM', 'Congés de matérnité'), ('MI', 'Mission'), ('P', 'Permission'), ('M', 'Maladie'), ('F', 'Formation'), ('REC', 'Récupération'), ('SS', 'Sur site')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
